name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  conform:
    runs-on: ubuntu-latest
    name: Validate commit

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  check:
    runs-on: ubuntu-latest
    name: Check Code
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '23'

      - name: Run Gradle Check # Runs PMD and Checkstyle
        run: ./gradlew check

  build:
    runs-on: ubuntu-latest
    name: Build Java application
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '23'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test


